version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: gui
      APP_PORT: 80

  gui:
    build: ./gui
    restart: on-failure
    depends_on:
      - api

  api:
    build: ./api
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      RPC_USER: ${LITECOIN_RPC_USER}
      RPC_PASSWORD: ${LITECOIN_RPC_PASSWORD}
      RPC_IP: ${LITECOIN_NODE_IP}
      RPC_PORT: "${LITECOIN_RPC_PORT}"
    depends_on:
      - litecoin

  litecoin:
    image: btcpayserver/litecoin:0.21.4
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "${LITECOIN_RPC_PORT}:9332"
      - "${LITECOIN_P2P_PORT}:9333"
    volumes:
      - ${APP_DATA_DIR}/.litecoin:/data/.litecoin
    environment:
      LITECOIN_NETWORK: mainnet
      LITECOIN_RPC_USER: ${LITECOIN_RPC_USER}
      LITECOIN_RPC_PASSWORD: ${LITECOIN_RPC_PASSWORD}
