version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: gui
      APP_PORT: 80

  gui:
    build: ./gui
    restart: on-failure
    depends_on:
      - api

  api:
    build: ./api
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      RPC_USER: gossimerlite
      RPC_PASSWORD: red2305
      RPC_IP: litecoin
      RPC_PORT: "9332"
    depends_on:
      - litecoin

  litecoin:
    image: btcpayserver/litecoin:0.21.4
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "9332:9332"
      - "9333:9333"
    volumes:
      - ${APP_DATA_DIR}/.litecoin:/data/.litecoin
    environment:
      LITECOIN_NETWORK: mainnet
      LITECOIN_RPC_USER: gossimerlite
      LITECOIN_RPC_PASSWORD: red2305
