version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: gui
      APP_PORT: 80

  litecoin:
    image: btcpayserver/litecoin:0.21.4
    restart: unless-stopped
    ports:
      - "9332:9332"
      - "9333:9333"
    volumes:
      - ${APP_DATA_DIR}/data:/data/.litecoin
    environment:
      LITECOIN_NETWORK: mainnet
      LITECOIN_RPC_USER: gossimerlite
      LITECOIN_RPC_PASSWORD: red2305

  api:
    build: ./api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      RPC_USER: gossimerlite
      RPC_PASSWORD: red2305
      RPC_IP: litecoin
      RPC_PORT: "9332"
    depends_on:
      - litecoin

  gui:
    build: ./gui
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
